### ISSUE TITLE
How to iInstall Pyspatialml

### ISSUE THREAD

**Issue by tanghailong0214** [stevenpawley/Pyspatialml#10]
there is problem when install Pyspatialml

**Comment by stevenpawley** [comment]
Can you provide the error output?

**Comment by masolele** [comment]
Error/Problem extracting raster values with polygon : UnboundLocalError: local variable 'rows' referenced before assignment

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-20-97661db69458> in <module>
      1 # Create a training dataset by extracting the raster values at the
      2 # training point locations:
----3 df_220 = stack.extract_vector(response=training_py220, columns='D_00_05')
   

~\AppData\Local\Continuum\anaconda3\envs\Time_series\lib\site-packages\pyspatialml\base.py in extract_vector(self, response, columns, return_array, duplicates, na_rm, low_memory)
    558         # spatial query of Raster object (loads each band into memory)
    559         if low_memory is False:
--> 560             X = self._extract_by_indices(rows, cols)
    561 
    562         # samples each point separately (much slower)

UnboundLocalError: local variable 'rows' referenced before assignment
