### ISSUE TITLE
Dataset types

### ISSUE THREAD

**Issue by dorotheeg** [stevenpawley/Pyspatialml#11]
Hello,

Thank you for this package! I was wondering, however, about the formats of you data sets. When I import the datasets it tells me "no module named 'pyspatialml.datasets'." Without seeing the types and shapes of the ones you use, adapting it makes it a bit more difficult. Do you happen to have raw data or formats of the raw data (types, column number, column headers…). 

Thank you for your help!

**Comment by stevenpawley** [comment]
Hello,

I hadn't updated the setup.py file for a while, so the datasets were not being installed (on a fresh install). It should be working now and you can import the example datasets. They are just small geotiff files.

Steve
