### ISSUE TITLE
Error/Problem extracting raster values with polygon : UnboundLocalError: local variable 'rows' referenced before assignment

### ISSUE THREAD

**Issue by masolele** [stevenpawley/Pyspatialml#12]
I have a shapefile with multiple polygons and time series of NDVI images, I wanted to extract the pixel values from each polygon for training and testing using Pyspatialml, but i am getting an error. Not sure if it is a bug. Thank you.

**Comment by stevenpawley** [comment]
Thanks for reporting this, I'll have a look this in the next day or so.
