### ISSUE TITLE
RasterioIOError: This is a BigTIFF file.  BigTIFF is not supported by this version of GDAL and libtiff.

### ISSUE THREAD

**Issue by tanghailong0214** [stevenpawley/Pyspatialml#13]
img_fp = r'.........\file.tif'
stack = Raster(img_fp)
but I am getting the following error message:
RasterioIOError: This is a BigTIFF file.  BigTIFF is not supported by this version of GDAL and libtiff.
I really don't know any solution. Can you offer some suggestion. Thank you!

**Comment by stevenpawley** [comment]
This sounds like an issue with your installed version of GDAL, that rasterio is using (and pyspatialml uses rasterio). Check to see if you have an old version of GDAL by running:

```
import rasterio
rasterio.gdal_version()
```

Maybe try updating / reinstalling GDAL?
