### ISSUE TITLE
cannot import nc_datasets

### ISSUE THREAD

**Issue by ritviksahajpal** [stevenpawley/Pyspatialml#16]
Thanks for a great package! A query, I get this error when trying to import nc_dataset

```
import pyspatialml.datasets.nc_dataset as nc
ModuleNotFoundError: No module named 'pyspatialml.datasets.nc_dataset'
```

Does nc_dataset need to be downloaded separately?

**Comment by stevenpawley** [comment]
Sorry for the confusion - I need to update the GitHub readme file. You can import the datasets using:

```
import pyspatialml.datasets.nc as nc
```

**Comment by ritviksahajpal** [comment]
excellent, thanks!!
