### ISSUE TITLE
TypeError in stack.extract_vector()

### ISSUE THREAD

**Issue by EChebelyon** [stevenpawley/Pyspatialml#17]
I am getting a `TypeError` when using the ```extract_vector()``` method.

Running:
```python
df_points = stack.extract_vector(gdf)
```
Returns:
```python
'TypeError': sample_gen() got an unexpected keyword argument 'masked'
```
`gdf` is a Geopandas geodataframe with two columns: a target and geometry column.

**Comment by stevenpawley** [comment]
Hmm, what version of rasterio do you have installed? Perhaps the 'masked' argument was for rasterio.sample.sample_gen was only added in a more recent version.

**Comment by EChebelyon** [comment]
Good flag, I was on `rasterio 1.1.0`  upgrading to `1.1.5` fixed the issue. 

Many thanks.
