### ISSUE TITLE
Export Output Map(result_probs) as '.tiff' file

### ISSUE THREAD

**Issue by tekeali** [stevenpawley/Pyspatialml#19]
Firstly, thank you for this code. 
I am trying to reclassify and evaluate the output map in GIS environment. How can I export this output map as '.tiff' file to my directory?

**Comment by stevenpawley** [comment]
Hi, sorry I'm not totally sure of what you mean. If you have made a classification map using pyspatialml, then you can simply use the `estimator.predict` method with a filename that ends with '.tif' and then open this within a GIS?

**Comment by tekeali** [comment]
Actually, my essential purpose is to produce susceptibility map. Firstly, I need to probability values of each pixels in the raster dataset. Then, I want to assign these probability values to raster pixels they belong to.

**Comment by bluetyson** [comment]
Like this :-
result_map = stack.predict(estimator=yourclassifiermodel, dtype='float32', nodata=-9999, file_path = r'C:\users\tekeali\DataOutputs\Susceptibility_Map.tif')

**Comment by stevenpawley** [comment]
Or for a susceptibility map, i.e. the probability of assignment to a particular class (e.g. to a binary target), you will want:

```
result = stack.predict_proba(estimator=your_fitted_model, dtype="float32", nodata=-99999, file_path="your_output_file.tif")
```
