### ISSUE TITLE
Compatible API question

### ISSUE THREAD

**Issue by bluetyson** [stevenpawley/Pyspatialml#21]
Hi Steven,

This looks really nice.  Reading the info, it mentions something with fit and predict should work.  I am interested in utilising the predict part on a raster stack with a model from elsewhere.

For example, NGBoost :- https://github.com/stanfordmlgroup/ngboost

Which is designed to be scikit-learn style.

Thanks,

Richard

**Comment by bluetyson** [comment]
Apparently, works very nicely!

NGBoost also has a pred_dist function to get the stdev parameter for example, which also made a fairly straightforward addition.

e.g. result_cla = estimator.pred_dist(flat_pixels)
       result_cla = result_cla.params['scale']

**Comment by RichardScottOZ** [comment]
see pull request for implementation
