### ISSUE TITLE
Errors in README

### ISSUE THREAD

**Issue by aazuspan** [stevenpawley/Pyspatialml#29]
Hi @stevenpawley, this is an awesome tool. Thanks for building it!

I came across a couple small issues in the readme, and I figured I'd point them out in case they confuse anyone else.

- In the three examples in the [Usage](https://github.com/stevenpawley/Pyspatialml#usage) section, files, arrays, and layers are passed to `file_path`, `arr`, and `layers` args, but they should all be passed to `src` instead. 
- According to the [Raster Prediction](https://github.com/stevenpawley/Pyspatialml#raster-prediction) section, the `predict_type` argument can be used to generate probabilities, but I think it doesn't do anything and `Raster.predict_proba()` should be used instead. Confusingly, `Raster.predict()` takes any kwargs, so it just ignores the `predict_type` if it's given and runs as usual. Maybe an error could be thrown for unrecognized kwargs?

**Comment by stevenpawley** [comment]
Thanks for this, definitely have been neglecting the readme for a while. Updated it now with working examples.
