### ISSUE TITLE
Creating RasterStack using more 6 predictors result into an error

### ISSUE THREAD

**Issue by samburu** [stevenpawley/Pyspatialml#3]
Please see if we can replace the following line in `to_pandas` method
`arr = arr.reshape((6, arr.shape[1] * arr.shape[2]))`
with
`arr = arr.reshape((arr.shape[0], arr.shape[1] * arr.shape[2]))`

**Comment by stevenpawley** [comment]
Thanks - a leftover from when I was experimenting with something. I have fixed this in the development branch where I'm making some structural changes to the package, but I'm not merging this back to master until I have settled on things. Fixed in master now.

**Comment by samburu** [comment]
Thank very much Steve. Very useful package for machine learning using spatial data.
