### ISSUE TITLE
When is the package ready to use?

### ISSUE THREAD

**Issue by flydream0428** [stevenpawley/Pyspatialml#4]
On the landing pager, it says the alpha version is expected to be ready in January 2019. I am wondering if it's ready now. : )

**Comment by stevenpawley** [comment]
Yes as I'm running a little behind. I have made quite a few changes recently, including mostly completing pandas-style indexing and slicing for the layers within the raster object, spatial querying to pandas dataframes, and converting the raster values to pandas dataframes for plotting purposes. I still have a few methods to implement, mostly simple wrappers around some of rasterio's functions, and some more work on setting the Raster object layers. I also plan to add some default plots for Raster and RasterLayer objects including being able to set the colour ramps for each raster layer in the Raster object, and plotting a single or multiple layers, similar to how it works in R's raster package. The landing page is also quite out-of-date in terms of usage. Hopefully by mid-next month these items will be finished.
