### ISSUE TITLE
Change needed on raster.py   Line   2563    pixel_indices = np.zeros(0, dtype=np.int)

### ISSUE THREAD

**Issue by venka-foss4g** [stevenpawley/Pyspatialml#49]
Line 2563  of raster.py need be edited

From: # pixel_indices = np.zeros(0, dtype=np.int)
To:         pixel_indices = np.zeros(0, dtype=np.int_)

As numpy.int was has been removed in NumPy >= 1.24

https://stackoverflow.com/questions/74946845/attributeerror-module-numpy-has-no-attribute-int

**Comment by gbganalyst** [comment]
Thank you, @venka-foss4g, I just changed mine too. I think it is good to create a pull request for these changes. I can take it up.
